profiles/urls.py
# -*- coding: utf-8 -*-

# Python

# Django
from django.contrib.auth.decorators import login_required
from django.urls                    import path

# Project
from .                              import views


urlpatterns = [
    path(
        route = 'signup/',
        view  = views.SignupUserView.as_view(),
        name  = 'signup'),
    path(
        route = 'login/',
        view  = views.LoginUserView.as_view(),
        name  = 'login'),
    path(
        route = 'logout/',
        view  = views.LogoutUserView.as_view(),
        name  = 'logout'),
    path(
        route = 'history/',
        view  = login_required(views.HistoryView.as_view()),
        name  = 'history'),
]

videos/urls.py
# -*- coding: utf-8 -*-

# Python

# Django
from django.urls import path

# Project
from .           import views

urlpatterns = [
    path(
        route = '',
        view  = views.VideoListView.as_view(),
        name  = 'list'),
    path(
        route = 'popular/',
        view  = views.VideoPopularListView.as_view(),
        name  = 'popular'),
    path(
        route = '<slug:slug>/',
        view  = views.VideoDetailView.as_view(),
        name  = 'detail'),
    path(
        route = '<str:youtube_id>/like',
        view  = views.like_video,
        name  = 'likes_video'
    ),
    path(
        route = '<str:youtube_id>/dislike',
        view  = views.dislike_video,
        name  = 'dislikes_video'
    ),
    path(
        route = '<str:youtube_id>/comment',
        view  = views.comment_video,
        name  = 'comment_video'
    ),
] 

youtube_clone/urls.py
# -*- coding: utf-8 -*-

# Python

# Django
from django.conf             import settings
from django.conf.urls.static import static
from django.contrib          import admin
from django.urls             import path, include
from videos.views            import VideoListView

# Project

urlpatterns = [
    path (route='', view=VideoListView.as_view(), name='list'),
    path('videos/', include(('videos.urls', 'videos'), namespace='videos')),
    path('admin/', admin.site.urls), 
    path('users/', include(('profiles.urls', 'profiles'), namespace='profiles')),
] 

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>YouTube clone</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css"  crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body class="h-100">
        {% include "nav.html" %}
    <div class="container h-100">
        {% block container %}
        
        {% endblock container %}
    </div>

    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    {% block scripts %}
    
    {% endblock scripts %}
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'videos:list'%}">Youtube clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'videos:popular' %}">Popular videos</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "profiles:history" %}">History</a>
                </li>
                <li>
                    <span class="nav-link">Hello {{user.username}}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "profiles:logout" %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "profiles:login" %}">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url "profiles:signup" %}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>