videos/urls.py
# -*- coding: utf-8 -*-

# Python

# Django
from django.urls import path

# Project
from .           import views

urlpatterns = [
    path(
        route = '',
        view  = views.VideoListView.as_view(),
        name  = 'list'),
    path(
        route = 'popular/',
        view  = views.VideoPopularListView.as_view(),
        name  = 'popular'),
    path(
        route = '<slug:slug>/',
        view  = views.VideoDetailView.as_view(),
        name  = 'detail'),
    path(
        route = '<str:youtube_id>/like',
        view  = views.like_video,
        name  = 'likes_video'
    ),
    path(
        route = '<str:youtube_id>/dislike',
        view  = views.dislike_video,
        name  = 'dislikes_video'
    ),
    path(
        route = '<str:youtube_id>/comment',
        view  = views.comment_video,
        name  = 'comment_video'
    ),
] 

youtube_clone/urls.py
# -*- coding: utf-8 -*-

# Python

# Django
from django.conf             import settings
from django.conf.urls.static import static
from django.contrib          import admin
from django.urls             import path, include
from videos.views            import VideoListView

# Project

urlpatterns = [
    path (route='', view=VideoListView.as_view(), name='list'),
    path('videos/', include(('videos.urls', 'videos'), namespace='videos')),
    path('admin/', admin.site.urls), 
    path('users/', include(('profiles.urls', 'profiles'), namespace='profiles')),
] 

videos/models.py
# -*- coding: utf-8 -*-

# Python

# Django
from django.db                  import models
from django.contrib.auth.models import User
from django.utils               import timezone

# Project

class Video(models.Model):
    
    title         = models.CharField(max_length=256, null=False)
    views         = models.IntegerField(null=False, default=0)
    author        = models.CharField(max_length=200)
    youtube_id    = models.CharField(max_length=50, null=False)
    thumbnail_url = models.URLField(max_length=200)
    slug          = models.SlugField(max_length=200,unique=True)
    likes         = models.ManyToManyField(User, blank=True)
    created_at    = models.DateTimeField(auto_now_add=True, null=True)
    dislikes      = models.ManyToManyField(User, related_name='dislike_videos', blank=True)
    comments      = models.ManyToManyField(User, through='Comment', related_name='comments_videos')
    active        = models.BooleanField(default=True)

    def __str__(self):
        return '{} by {}'.format(self.title, self.author)

    def calculate_popularity(self):
        value_for_likes    = len(self.likes.all()) * 10
        value_for_comments = len(self.comments.all()) 
        dislikes           = len(self.dislikes.all()) 
        if dislikes > 0:
            value_for_dislikes = dislikes * 5
        else:
            value_for_dislikes = 0

        if self.created_at.date() == timezone.now().date():
            today_bonus = 100
        else:
            today_bonus = 0

        total = (value_for_likes + value_for_comments + today_bonus) - value_for_dislikes 

        return total


class Comment(models.Model):
    video      = models.ForeignKey(Video, on_delete=models.CASCADE)
    user       = models.ForeignKey(User, on_delete=models.CASCADE)
    comment    = models.CharField(max_length=300, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return '{} by {}'.format(self.created_at, self.user.username)

videos/views.py
# -*- coding: utf-8 -*-

# Python

# Django
from django.contrib.auth.decorators import login_required
from django.core                    import serializers
from django.db.models               import Count
from django.http                    import JsonResponse
from django.shortcuts               import render, redirect
from django.urls                    import reverse_lazy
from django.utils                   import timezone
from django.views.decorators.http   import require_http_methods
from django.views.generic           import ListView, DetailView, View

# Project
from .models                        import Video, Comment
from profiles.models                import History

class VideoListView(ListView):
    model         = Video
    template_name = "videos/list.html"
    paginate_by   =  10

class VideoPopularListView(ListView):
    model               = Video
    template_name       = "videos/popular.html"
    context_object_name = 'videos'

    def get_queryset(self):
        queryset = sorted(Video.objects.all()
            .order_by('-created_at')
            .exclude(created_at=None), 
                key=lambda popularity: popularity.calculate_popularity(), 
                reverse=True)[:5]
        if len(queryset) < 5:
            queryset = sorted(Video.objects.all()
                .order_by('-created_at'), 
                    key=lambda popularity: popularity.calculate_popularity(), 
                    reverse=True)[:5]            
        return queryset

class VideoDetailView(DetailView):
    model=Video
    template_name="videos/detail.html"
    query_set=Video.objects.all()
    slug_field="slug"
    slug_url_kwarg="slug"

    def get_context_data(self, **kwargs):
        ContextOfTheView=super().get_context_data(**kwargs)
        video=self.get_object()
        if self.request.user.is_authenticated:
            History.objects.create(
                user  = self.request.user,
                video = video
            )
        likes = Video.objects.filter(youtube_id=video.youtube_id).aggregate(dislikes_count=Count('dislikes'), likes_count=Count('likes'))
        ContextOfTheView["comments"]= Comment.objects.filter(video=video)
        ContextOfTheView["likes"]   = likes
        return ContextOfTheView



    def render_to_response(self, context, **response_kwargs):
        video       = self.get_object()
        video.views = video.views + 1
        video.save()
        
        return super().render_to_response(context, **response_kwargs)

@require_http_methods(["POST"])
def comment_video(request, youtube_id):
    user_logged = request.user
    video       = Video.objects.get(youtube_id=youtube_id)
    comment_req = request.POST.get("comment")
    
    comment     = Comment.objects.create(
        video   = video,
        user    = user_logged,
        comment = comment_req
    )

    return redirect(reverse_lazy("videos:detail", kwargs={"slug": video.slug}))

@require_http_methods(["POST"])
def like_video(request, youtube_id):
    if request.user.is_authenticated:
        user_logged=request.user
        video=Video.objects.filter(youtube_id=youtube_id).first()

        if not video:
            return JsonResponse({'error': 'invalid video id'}, status=400)

        if not user_logged in video.likes.all():

            video.likes.add(user_logged)
            video.dislikes.remove(user_logged)
            video.save()

            response={
                "status"   :  True,
                "response" : "Like saved"
            }
        else: 
            response = {
                "status"   :  False,
                "response" : "Already Liked"
            }
    else:
        response = {
                "status"   :  False,
                "response" : "Only user can like videos"
        }
    return JsonResponse(response)

@require_http_methods(["POST"])
def dislike_video(request, youtube_id):
    if request.user.is_authenticated:
        user_logged = request.user
        video       = Video.objects.filter(youtube_id=youtube_id).first()

        if not video:
            return JsonResponse({'error': 'invalid video id'}, status=400)    
        
        if not user_logged in video.dislikes.all():

            video.dislikes.add(user_logged)
            video.likes.remove(user_logged)
            video.save()

            response={
                "status"   :  True,
                "response" : "Dislike saved"
            }
        else: 
            response = {
                "status"   :  False,
                "response" : "Already Disliked"
            }
    else:
        response = {
                "status"   :  False,
                "response" : "Only user can dislike videos"
        }

    return JsonResponse(response)

videos/templates/videos/detail.html
{% extends "base.html" %}

{% block container %}

    <div class="row mt-5">
        <div class="col-sm-8 offset-sm-2">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{object.youtube_id}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
        </div>

        <div class="col-sm-8 offset-sm-2 mt-3">
            <h3>{{object.title}}</h3>
            <span>
                <small>By</small>
                {{object.author}}
            </span>
            <span>{{object.views}} views
            </span>
        </div>

        <div class="col-sm-8 offset-sm-2 mt-3">
            <a class="like">
                <span id="likes_count">{{likes.likes_count}}</span>
                <i class="far fa-thumbs-up"></i>
            </a>
            <a class="dislike">
                <span id="dislikes_count">{{likes.dislikes_count}}</span>
                <i class="far fa-thumbs-down"></i>
            </a>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-sm-8 offset-sm-2">
            <form action="{% url 'videos:comment_video' object.youtube_id %}" method="POST" id="comment_video">
                {% csrf_token %}
                <textarea 
                    name="comment" 
                    id="comment" 
                    cols="2" 
                    rows="2" 
                    class="form-control w-100" 
                    required
                    placeholder="Write your comment here..."
                    style="color:black;"
                ></textarea>
                <button class="btn btn-primary mb-2 mt-2" type="submit" {% if not user.is_authenticated  %} disabled {% endif %}>Comment</button>
            </form>
        </div>
    </div>
    
    <div class="row mt-5">
        <div class="col-sm-8 offset-sm-2">
            <h3>Comments: </h3>
            {% for comment in comments %}
                <div class="card w-100 mt-2">
                    <div class="card-body">
                        <h5 class="card-title">By: {{comment.user.username}}</h5>
                        <p class="card-text">{{comment.comment}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock container %}


{% block scripts %}

<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    
    $('.like').click(() => {
        console.log('like');
        $.post("{% url 'videos:likes_video' object.youtube_id %}", {}, function(result) {
            console.log(result);
            if (result['status']) {
                let value = $('#likes_count').text();
                $('#likes_count').text(parseInt(value, 10) + 1);
            }
        })
    });

    $('.dislike').click(() => {
        console.log('dislike');
        $.post("{% url 'videos:dislikes_video' object.youtube_id %}", {}, function(result) {
            console.log(result);
            if (result['status']) {
                let value = $('#dislikes_count').text();
                $('#dislikes_count').text(parseInt(value, 10) + 1);
            }
        })
    });

</script>

{% endblock scripts %}

videos/templates/videos/list.html
{% extends "base.html" %}

{% block container %}

<div class="row mt-5">
    <div class="col col-sm-8 offset-sm-2">
        <h1 class="text-center">Video List</h1>
        {% for video in object_list %}
        <div class="card w-100 mt-4">
            <div class="card-body">
                <h5 class="card-title">{{video.title}}</h5>
                <img src="{{video.thumbnail_url}}" class="img-thumbnail" alt="{{video.slug}}-thumbnail">
                <p class="card-text">By: {{video.author}}</p>
                <a href="/videos/{{video.slug}}/" class="btn btn-primary">Ver</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="row mt-5 align-items-center">
    <div class="col col-sm-8 offset-sm-4">
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                {% ifequal num page_obj.number %}
                <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endifequal %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="disabled"><a href="#">&raquo;</a></li>
                {% endif %}

            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock container %}

videos/templates/videos/popular.html
{% extends "base.html" %}

{% block container %}
    

    <div class="row mt-5">
        <div class="col col-sm-8 offset-sm-2">
            <h1 class="text-center">Video Popular List</h1>
            {% for video in object_list %}
                <div class="card w-100 mt-4">
                    <div class="card-body">
                    <h5 class="card-title"><label class="text-primary">#{{ forloop.counter }}</label> | {{video.title}}</h5>
                    <img src="{{video.thumbnail_url}}" class="img-thumbnail" alt="{{video.slug}}-thumbnail">
                    <h6>Popularity: {{video.calculate_popularity}} | <small>{{video.created_at}}</small></h6>
                    <p class="card-text">By: {{video.author}}</p>
                    <a href="/videos/{{video.slug}}/" class="btn btn-primary">Ver</a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock container %}